language: cpp
dist: xenial
env:
  global:
    secure: "Fd2JSFkAGWSt0jddzHnyNYDDS2gbEaHEGJzGpbpvBr3AuS9JdWOsh3mgQ+6d+i7mMmaq52En+rWTgjpoe9I9WtZCakK9kxj3WKHVJhxEFKeUeB2SRERX7WtFNwfC7jZPHe0cSY5kDv4o9V09bV+afUsEl53jyRjk/XWDxVKZ9irGFR5pywvcY12FrkHDuxWBmbMY2Ha2g4U0UmHM2p9E3fjbqL/t32XDlKKOfVTcFLSNe4NcZ9yQPFD6D2gBh6Gb2wrBoWOYdnfVm3RBdBoGXgD9/00BTjbX2JF4JEkFJI/pw5pldcNbhz05EsQK9ooxsoFAIPAZ2J56RGotjiPUm6h9OOSdy6T7dB7AFT0xjhgX17po0Ihc9ViFlRzunExACsKzBfLeKOzN7+Z4mybb+duxxXfChj5g4RsAoCsZmUxD4FfHqnFxirtNYKRUKPzlgNXdGUwjZw1wruXUlzP0WS7ML694+yvEwHv5k1lsWgwzOsa93jAVyEKLhKs/4BuzQjm5LZjTgOdwOLHu8PaeUMEoy6TizzuHI85HCim0ExCZJiCUCx4/JQoG0Dj7P0iprBgdZbdBQMp8nfUBnO8NF+1xwO13oTKnRCwCpBRFln6GhlkWZDRnFT+JY3yyWPx0OLQKPl2KTuLz+1sgz/IvW6ElkgAIUn4gJ3fLrhfAwes="
matrix:
  include:
    - os: linux
      env:
        - BuildType = "Cppcheck & MISRA C 2012"
      script: scripts/cppcheck.sh

    - os: linux
      env:
        - BuildType = "Coverall"
      before_install:
        - pip install --user cpp-coveralls
      script: scripts/coverage.sh
      after_success:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

    - os: linux
      env:
        - BuildType = "Coverity scan"
      if: type != push AND type != pull_request
      script:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: "sil4oss/hello-world"
          description: "Hello World"
        notification_email: huchijwk@gmail.com
        build_command: "scripts/build.sh"
        branch_pattern: master
